FROM apache/airflow:2.9.3-python3.11

USER root
RUN python -m pip install --no-cache-dir apache-airflow-providers-postgres psycopg2-binary && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

USER airflow

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

EXPOSE 8080